spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library-dev # For local use
#    url: jdbc:mysql://host.docker.internal:3306/library-dev # For container use
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Pass1234

management: # For actuator
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'