server:
  port: 8072

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # No need to register itself
    fetchRegistry: false # No need to fetch info of other services from eureka coz it holds the info itself
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/