spring:
  profiles:
    active: dev # Required for seeking correct config.yaml from config server -> {application name}-{profile}.yaml
  #    active: ${ACTIVE_PROFILES}
  application:
    name: gateway # Required for seeking config.yaml from config server -> {application name}.yaml
  config:
    import: configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Default true, determine if system fetch locator info from eureka
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs # can be found in keycloak http://localhost:8080/realms/master/.well-known/openid-configuration

eureka:
  instance:
    preferIpAddress: true # by default register as hostname
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8072/eureka/

# Micrometer related properties
management:
  tracing:
    sampling:
      probability: 1.0 # By default, only 10% logs would be sent to zipkin for preventing performance issues in big scale projects
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # zipkin api endpoint
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
