spring:
  profiles:
    active: dev # Required for seeking correct config.yaml from config server -> {application name}-{profile}.yaml
  #    active: ${ACTIVE_PROFILES}
  application:
    name: gateway # Required for seeking config.yaml from config server -> {application name}.yaml
  config:
    import: configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Default true, determine if system fetch locator info from eureka
          lowerCaseServiceId: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token # where your app can get an access token once user consent has been granted
            authorization-uri: http://localhost:8080/realms/master/protocol/openid-connect/auth # where users input the credentials
            userinfo-uri: http://localhost:8080/realms/master/protocol/openid-connect/userinfo # where the application to fetch user details
            user-name-attribute: preferred_username
        registration:
          library-gateway: # whatever name you want
            provider: keycloak
            client-id: library-gateway-ui
            secret: 66iCs7FBVVtGTRUnT8q55yBY4w0DG3TM
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs # can be found in keycloak http://localhost:8080/realms/master/.well-known/openid-configuration

eureka:
  instance:
    preferIpAddress: true # by default register as hostname
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8072/eureka/

# Micrometer related properties
management:
  tracing:
    sampling:
      probability: 1.0 # By default, only 10% logs would be sent to zipkin for preventing performance issues in big scale projects
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # zipkin api endpoint
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
