spring:
  profiles:
    active: dev # Required for seeking correct config.yaml from config server -> {application name}-{profile}.yaml
  #    active: ${ACTIVE_PROFILES}
  application:
    name: gateway # Required for seeking config.yaml from config server -> {application name}.yaml
  config:
    import: configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Default true, determine if system fetch locator info from eureka
          lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true # by default register as hostname
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8072/eureka/

# Micrometer related properties
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
